[package]
name = "rs-fmsynth"
version = "0.1.0"
authors = ["Roland Ballinger <roland2@pdx.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

portaudio   = "*"
fltk        = "^0.2.14"
